Update Department.h
itstep-shambala/Hospital pull request #1
Opened 2020-10-18 12:21 UTC by SushkowAndrey

2020-10-23 09:17 UTC, anst-foto requested changes
Исправить замечания.
Почитать про `.gitignore` - т.к. много лишних файлов.

2020-10-23 09:17 UTC, anst-foto commented on Doctor.h
> +		cout << "������������� � ��������� - " << specialization << endl;
Проблемы с кодировкой русских букв...

2020-10-23 09:17 UTC, anst-foto commented on Export.h
> +	}
Что за интересный способ работы с исключениями?

2020-10-23 09:17 UTC, anst-foto commented on Header.h
> +    }
Почему 10 возвращается?

2020-10-23 09:17 UTC, anst-foto commented on Import.h
> +using namespace std;
Интересное решение для уменьшения написания кода ))))

2020-10-23 09:17 UTC, anst-foto commented on Interface.h
> +        cout << "=== ����������� �������� ===" << endl;
Кодировка...

2020-10-23 09:17 UTC, anst-foto commented on Interface.h
> +        cout << "������� ���������� ���������� ������������" << endl;
Кодировка

2020-10-23 09:17 UTC, anst-foto commented on Interface.h
> +        cout << "������� ���������� �������� ������������" << endl;
Кодировка

2020-10-23 09:17 UTC, anst-foto commented on Interface.h
> +        cout << "0. �����" << endl;
Кодировка

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +#include <string>
Зачем ещё раз подключать `string` если уже используете его в `Interface.h`?

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +            }
Много кода - лучше создать отдельную функцию.

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +            }
Повторяющийся код - нужна функция.

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +            }
Повторяющийся код - нужна функция.

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +            }
Повторяющийся код - нужна функция.

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +            }
Повторяющийся код - нужна функция.

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +    Doctor* doctor = new Doctor[Number_of_doctors];
Лучше использовать `vector`

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +    Nurse* nurse = new Nurse[Number_of_nurses];
Лучше использовать `vector`

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +}
Лучше вынести в отдельный файл

2020-10-23 09:17 UTC, anst-foto commented on main.cpp
> +}
Лучше вынести в отдельный файл

2020-10-23 09:32 UTC, SushkowAndrey commented on Header.h
> +    }
при проверке введенного числа если оно не соответствует параметрам, которые указаны в данной функции, то возвращается число, которого нет в меню и выдается сообщение ERROR

2020-10-23 09:34 UTC, SushkowAndrey commented on Import.h
> +using namespace std;
данный файл пока не завершен

2020-10-23 09:34 UTC, SushkowAndrey commented on main.cpp
> +}
скорректирую

2020-10-23 09:34 UTC, SushkowAndrey commented on main.cpp
> +}
скорректирую

2020-10-23 09:35 UTC, SushkowAndrey commented on main.cpp
> +    Nurse* nurse = new Nurse[Number_of_nurses];
скорректирую

2020-10-23 09:35 UTC, SushkowAndrey commented on main.cpp
> +    Doctor* doctor = new Doctor[Number_of_doctors];
скорректирую

2020-10-23 09:37 UTC, SushkowAndrey commented on Export.h
> +	}
это увидел в видеоуроке https://www.youtube.com/watch?v=jCW2wRoRi0U&list=PLQOaTSbfxUtBm7DxblJZShqBQnBAVzlXX&index=56&t=6s (время 9.20), но не проверял как будет работать, не дописана функция

2020-10-23 09:54 UTC, SushkowAndrey commented on Doctor.h
> +		cout << "������������� � ��������� - " << specialization << endl;
с эти уже сталкивался, не разобрался с причиной

2020-10-23 09:54 UTC, SushkowAndrey commented on Interface.h
> +        cout << "=== ����������� �������� ===" << endl;
с эти уже сталкивался, не разобрался с причиной

2020-10-23 10:59 UTC, anst-foto commented on Doctor.h
> +		cout << "������������� � ��������� - " << specialization << endl;
Попробуйте открыть файлы в **Notepad++** и в нём изменить кодировку на **UTF-8 без BOM**

2020-10-23 11:00 UTC, anst-foto commented on Export.h
> +	}
Плохо, что не проверили.

2020-10-23 11:00 UTC, anst-foto commented on Header.h
> +    }
Не хватает документации...

2020-10-23 11:01 UTC, anst-foto commented on Import.h
> +using namespace std;
Тогда плохо получать недоделки (((

2020-10-23 11:01 UTC, anst-foto commented on Interface.h
> +        cout << "=== ����������� �������� ===" << endl;
https://github.com/itstep-shambala/Hospital/pull/1#discussion_r510804693

2020-10-23 11:02 UTC, anst-foto commented on Interface.h
> +        cout << "������� ���������� ���������� ������������" << endl;
https://github.com/itstep-shambala/Hospital/pull/1#discussion_r510804693

2020-10-23 11:02 UTC, anst-foto commented on Interface.h
> +        cout << "������� ���������� �������� ������������" << endl;
https://github.com/itstep-shambala/Hospital/pull/1#discussion_r510804693

2020-10-23 11:02 UTC, anst-foto commented on Interface.h
> +        cout << "0. �����" << endl;
https://github.com/itstep-shambala/Hospital/pull/1#discussion_r510804693

2020-10-30 08:22 UTC, anst-foto commented
Изменения выполнены в #2

2020-10-30 08:22 UTC, closed without merging